name: Android Development CI

on:
  push:
    branches: [ "cicd" ]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Grant execute permissions
        run: chmod +x /home/runner/work/RajawaliAir/RajawaliAir/gradlew
      - uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'beta'
      - uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: app/build/outputs/apk/**/*.apk